### ISSUE TITLE
2 issues. Self disabling and wrong crash logfile default name

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#3]
Error on selfdisabling feature and inaccessible default logfile name when saving crash dump.

[crash-2024.txt](https://github.com/user-attachments/files/16849543/crash-2024.txt)

**Comment by Sparronator9999** [comment]
It looks like I can reproduce both issues on my end.

For the crash report saving issue, it looks like my sh*tty code is trying to set a default filename with colons ":" in it (which aren't allowed in a filename in Windows).

This is what happens when you don't test features, people...

I will fix both issues later.

**Comment by Sparronator9999** [comment]
Hi, can you please test the latest build from GitHub Actions when it finishes?

Both issues are now fixed on my end.

**Comment by porkmanager** [comment]
> Both issues are now fixed on my end.

Yep. Ive just tried latest build and it has been fixed. Thank u!

**Comment by Sparronator9999** [comment]
No problem!
