### ISSUE TITLE
Cmd? and Performance mode

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#4]
1. Can I ask you to share cmd commands of yamdcc? I read that is present in app and still wip. Can I try already released commands?
Also I want to suggest some features with the command line:
- load and apply config
- restart service 
- probably switch fan profile( but feels like that is not necessary. as for me it is simpler to make config and only one fan profile per config)

2. is there any difference btween performance modes high and balanced? Seems those both had no additional power limits like max.battery mode has 10w limit for cpu and silent mode seems should limit cpu to 20w(didnt tested that mode in yamdcc yet but in msi center was). And one thing about max battery perf.mode, msi center disabling keyboard lighting when enabled max battery mode iirc

**Comment by Sparronator9999** [comment]
1:

I probably should have made this clearer, but the CLI will be a separate app from the GUI config app. In other words, there are no commands built into the GUI configurator. I will clarify this in the README in a commit.

As for your suggestions, I aim for the CLI to do most, if not all of the things that the GUI does, just via command line. Although I might look into the restart service function in the GUI, now that you mention it.

2:

I don't think there's a difference between high and balanced performance. In fact, if I remember correctly, MSI Center doesn't set what YAMDCC calls the Balanced mode in its equivalent menu. I included it because it *might* make a difference on someone's laptop.

As for the keyboard light disabling feature of MSI Center when set to max battery, this actually isn't caused by setting the Max Battery mode in EC, and instead appears to be MSI Center also changing the backlight setting. I could add a keyboard backlight control, but there's already shortcuts on the keyboard that achieve the same thing, so I didn't include it.

**Comment by porkmanager** [comment]
> I could add a keyboard backlight control, but there's already shortcuts on the keyboard that achieve the same thing, so I didn't include it.

I think that isnt usless feature, for example it gives possibility to operate backlit from external keyboard

**Comment by Sparronator9999** [comment]
> scenario: using external kb with the connected to tv laptop in the dark XD). So you should not to stand up for turn off that shiny thing

Hmm, that's a good point. I'll add it to the to-do list.
