### ISSUE TITLE
Saved config view

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#7]
Here is how your config looks in editor:
![image](https://github.com/user-attachments/assets/32edee52-734e-412e-aefd-9fa1bb3d78da)

And here is how looks like saved config from yamdcc:
![image](https://github.com/user-attachments/assets/4aa3998a-9012-493b-b53a-6a60e62e0589)

In web browser window saved config looks properly, thats happenin just in text editor
![image](https://github.com/user-attachments/assets/813231c5-626c-4e99-9bbe-b7653d1285c3)

Not a big issue

**Comment by Sparronator9999** [comment]
About that... it's kind of intentional when saving to the service's working config (`CurrentConfig.xml`), to save configs that look like that.

As for configs saved by the user to an XML wherever they choose (e.g. Desktop), you're right, they might want it to be "beautified" XML for easier editing (especially since you can't edit everything in a config from the configuration app).

I will look into this.

**Comment by Sparronator9999** [comment]
The latest commit has a fix for this issue.
